apiVersion: v1
kind: ConfigMap
metadata:
  name: kodey-boilerplate-config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "warn"
  CORS_ORIGIN: "https://kodey.com,https://app.kodey.com"
  THROTTLE_LIMIT: "100"
  CACHE_TTL: "600"
  CACHE_MAX: "10000"