apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kodey-boilerplate

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- configmap-patch.yaml

images:
- name: kodey-boilerplate
  newTag: "v1.0.0"

commonLabels:
  environment: production

replicas:
- name: kodey-boilerplate
  count: 5